/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class br_ufabc_bassani_jmf_firewire_media_protocol_fwc_FireWireCamera */

#ifndef _Included_br_ufabc_bassani_jmf_firewire_media_protocol_fwc_FireWireCamera
#define _Included_br_ufabc_bassani_jmf_firewire_media_protocol_fwc_FireWireCamera
#ifdef __cplusplus
extern "C" {
#endif
/* Inaccessible static: frameRate */
/* Inaccessible static: width */
/* Inaccessible static: height */
/* Inaccessible static: format */
/*
 * Class:     br_ufabc_bassani_jmf_firewire_media_protocol_fwc_FireWireCamera
 * Method:    vendor
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_br_ufabc_bassani_jmf_firewire_media_protocol_fwc_FireWireCamera_vendor
  (JNIEnv *, jobject);

/*
 * Class:     br_ufabc_bassani_jmf_firewire_media_protocol_fwc_FireWireCamera
 * Method:    model
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_br_ufabc_bassani_jmf_firewire_media_protocol_fwc_FireWireCamera_model
  (JNIEnv *, jobject);

/*
 * Class:     br_ufabc_bassani_jmf_firewire_media_protocol_fwc_FireWireCamera
 * Method:    configure
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_br_ufabc_bassani_jmf_firewire_media_protocol_fwc_FireWireCamera_configure
  (JNIEnv *, jobject);

/*
 * Class:     br_ufabc_bassani_jmf_firewire_media_protocol_fwc_FireWireCamera
 * Method:    setCaptureFormat
 * Signature: (IIII)V
 */
JNIEXPORT void JNICALL Java_br_ufabc_bassani_jmf_firewire_media_protocol_fwc_FireWireCamera_setCaptureFormat
  (JNIEnv *, jobject, jint, jint, jint, jint);

/*
 * Class:     br_ufabc_bassani_jmf_firewire_media_protocol_fwc_FireWireCamera
 * Method:    getFrame
 * Signature: ()[B
 */
JNIEXPORT jbyteArray JNICALL Java_br_ufabc_bassani_jmf_firewire_media_protocol_fwc_FireWireCamera_getFrame__
  (JNIEnv *, jobject);

/*
 * Class:     br_ufabc_bassani_jmf_firewire_media_protocol_fwc_FireWireCamera
 * Method:    getFrame
 * Signature: ([B)V
 */
JNIEXPORT void JNICALL Java_br_ufabc_bassani_jmf_firewire_media_protocol_fwc_FireWireCamera_getFrame___3B
  (JNIEnv *, jobject, jbyteArray);

/*
 * Class:     br_ufabc_bassani_jmf_firewire_media_protocol_fwc_FireWireCamera
 * Method:    start
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_br_ufabc_bassani_jmf_firewire_media_protocol_fwc_FireWireCamera_start
  (JNIEnv *, jobject);

/*
 * Class:     br_ufabc_bassani_jmf_firewire_media_protocol_fwc_FireWireCamera
 * Method:    stop
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_br_ufabc_bassani_jmf_firewire_media_protocol_fwc_FireWireCamera_stop
  (JNIEnv *, jobject);

/*
 * Class:     br_ufabc_bassani_jmf_firewire_media_protocol_fwc_FireWireCamera
 * Method:    cleanUp
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_br_ufabc_bassani_jmf_firewire_media_protocol_fwc_FireWireCamera_cleanUp
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
